# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hremployee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=4000)),
                ('mobile_number', models.CharField(max_length=4000, null=True)),
                ('year_exp', models.IntegerField(null=True)),
                ('personal_email', models.CharField(max_length=4000, null=True)),
                ('first_name', models.CharField(max_length=4000, null=True)),
                ('middle_name', models.CharField(max_length=4000, null=True)),
                ('last_name', models.CharField(max_length=4000, null=True)),
                ('employee_no', models.CharField(max_length=4000, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('address', models.CharField(max_length=4000, null=True)),
                ('permanent_address', models.CharField(max_length=4000, null=True)),
                ('emp_image', models.CharField(max_length=4000, null=True)),
                ('emp_role', models.CharField(max_length=4000, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('created_date', models.DateField(null=True)),
                ('updated_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'hremployee',
            },
        ),
    ]
