# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-19 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('email_id', models.CharField(max_length=4000)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(null=True)),
                ('status_id', models.IntegerField()),
                ('jobtitle_id', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=4000, null=True)),
                ('created_by', models.IntegerField()),
                ('office_number', models.CharField(max_length=4000, null=True)),
                ('isactive', models.IntegerField()),
                ('modified_by', models.IntegerField(null=True)),
                ('year_exp', models.IntegerField()),
                ('businessunit_id', models.IntegerField()),
                ('manager_id', models.IntegerField(null=True)),
                ('modified_date', models.DateTimeField(null=True)),
                ('created_date', models.DateTimeField()),
                ('personal_email', models.CharField(max_length=4000)),
                ('first_name', models.CharField(max_length=4000)),
                ('middle_name', models.CharField(max_length=4000, null=True)),
                ('last_name', models.CharField(max_length=4000)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=4000)),
                ('permanent_address', models.CharField(max_length=4000)),
                ('office_location_id', models.IntegerField()),
                ('emp_dm_id', models.CharField(max_length=4000)),
                ('emp_image', models.CharField(max_length=4000, null=True)),
                ('resignation_date', models.DateTimeField(null=True)),
                ('reason_of_leaving', models.CharField(max_length=8000, null=True)),
                ('emp_role', models.CharField(max_length=4000, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='employee_dependents',
            fields=[
                ('dependent_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.BigIntegerField()),
                ('dependent_name', models.CharField(max_length=4000)),
                ('relation', models.CharField(max_length=4000)),
                ('dob', models.DateField()),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_dependents',
            },
        ),
        migrations.CreateModel(
            name='employee_designationpackagehistory',
            fields=[
                ('pckg_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('salary', models.FloatField()),
                ('from_date', models.DateField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('active', models.IntegerField()),
                ('currency_id', models.BigIntegerField()),
                ('designation_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'employee_designationpackagehistory',
            },
        ),
        migrations.CreateModel(
            name='employee_doc',
            fields=[
                ('docId', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.BigIntegerField()),
                ('doc_name', models.CharField(max_length=2000)),
                ('upload_doc_name', models.CharField(max_length=2000, null=True)),
                ('modified_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_doc',
            },
        ),
        migrations.CreateModel(
            name='employee_education',
            fields=[
                ('emp_edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.BigIntegerField()),
                ('school_univeristy_name', models.CharField(max_length=3000)),
                ('qualification_degree_name', models.CharField(max_length=1000)),
                ('date_of_completion', models.DateField()),
                ('notes', models.CharField(max_length=1000)),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_education',
            },
        ),
        migrations.CreateModel(
            name='employee_experience',
            fields=[
                ('emp_expr_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.BigIntegerField()),
                ('prev_company_name', models.CharField(max_length=5000)),
                ('job_title', models.CharField(max_length=2500)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('job_description', models.CharField(max_length=5000)),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'employee_experience',
            },
        ),
        migrations.CreateModel(
            name='employee_project',
            fields=[
                ('emp_proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.BigIntegerField()),
                ('project_id', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.BigIntegerField()),
                ('created_date', models.DateTimeField()),
                ('billing_type', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'employee_project',
            },
        ),
        migrations.CreateModel(
            name='employee_type',
            fields=[
                ('emp_typeId', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'employee_type',
            },
        ),
    ]
