# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hremployee',
            name='personal_email',
        ),
    ]
