# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0002_remove_hremployee_personal_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hremployee',
            name='birth_date',
        ),
    ]
