# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0002_auto_20180620_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_dm_id',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
