# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-09 08:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0003_auto_20180620_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_experience',
            name='created_by',
        ),
    ]
