# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0005_auto_20180709_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='resign_status',
            field=models.IntegerField(null=True),
        ),
    ]
