# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-11 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0006_employee_resign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager_resignation_comment',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
