# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_employee', '0007_employee_manager_resignation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='resignation_date',
            field=models.DateField(null=True),
        ),
    ]
