# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_master',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
