# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-25 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0003_auto_20180625_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase_order',
            name='po_billing_per_hour',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='po_billing_type',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='po_project_cost',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='po_resource_count',
        ),
    ]
