# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0004_auto_20180625_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_master',
            name='customer_id',
        ),
    ]
