# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0005_remove_project_master_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_master',
            name='customer_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
