# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0006_project_master_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_table',
            name='active',
        ),
    ]
