# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0007_remove_customer_table_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_table',
            name='active',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
