# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0008_customer_table_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_master',
            name='project_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
