# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0010_auto_20180709_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='payment_received_flag',
            field=models.IntegerField(null=True),
        ),
    ]
