# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0011_purchase_order_payment_received_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='payment_received_flag',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
