# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0012_auto_20180713_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='po_payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_id', models.BigIntegerField()),
                ('received_date', models.DateField(null=True)),
                ('created_date', models.DateField(null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_date', models.DateField(null=True)),
            ],
        ),
    ]
