# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0013_po_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_payment',
            name='cheque_tnx_no',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
