# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0014_po_payment_cheque_tnx_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_payment',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
