# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-13 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0015_po_payment_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='po_payment',
            table='po_payment',
        ),
    ]
