# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-17 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_admin', '0016_auto_20180713_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_table',
            name='private_key',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='customer_table',
            name='public_key',
            field=models.CharField(max_length=4000, null=True),
        ),
    ]
